version: "3.9"

services:
  token-analyzer:
    # environment:
    #   - ENV=production
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend          # ← points to frontend folder
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    depends_on:
      - token-analyzer
    environment:
      - BASE_URL=http://token-analyzer:8000